### PR TITLE
Fixes for 39C3 release

### LINKED ISSUE #1595: Fix pagination and sorting order for the admin "All users"-page
With the new pagination of the admin "All users"-page the sorting now works in an unexpected way. Instead of sorting all users by the chosen column and then paginating over the results it first paginates the users and then sorts only on the user-chosen page. For example it is not possible to find all users who have been freeloaded while using the pagination.

Also when clicking on a column header to sort I would expect the chosen page size to stay the same, currently it resets back to the default.

To achieve this we probably need to move the sorting into the database query, which seems to be non-trivial, as some columns are computed later.

### PR DESCRIPTION
**Pull request by MyIgel**
* Log location name when changing shift
* Log token on JWT error
* Show message on own shifts page when freeloaded
* 39c3 design:
  * Fix selected bg color in searchable drowdown
  * Fix color of progress bar on shift
* Fix users sorting in shift
* Allow searching users by contact infos
* Fix string input length validation date detection (broke when saving `p3000` as worklog description)
* Fix en_US plural texts, update de_DE text
* Fix saving user while email human gets enabled which resulted in db error (email can't be null)
* Fix /users paginated sorting & cleanup, closes #1595

### CODE REVIEW

File: includes/controller/shifts_controller.php [hunk 1]
```diff
@@ -191,6 +191,7 @@ function shift_edit_controller()
                 'Updated shift \'' . $shifttypes[$shifttype_id] . ', ' . $title
                 . '\' from ' . $start->format('Y-m-d H:i')
                 . ' to ' . $end->format('Y-m-d H:i')
+                . ' in ' . $locations[$rid]
```
Comment (xuwhite) [inline includes/controller/shifts_controller.php:194]: please also add this to shift deletions

File: resources/lang/en_US/default.po [hunk 2]
```diff
@@ -16,6 +16,18 @@ msgstr ""
 "Language: en_US\n"
 "X-Poedit-SearchPath-0: .\n"
 
+# Translated plural form must exist to be shown
+msgid "There are unconfirmed angels in %d angel type. Angel type that needs approval:"
+msgid_plural "There are unconfirmed angels in %d angel types. Angel types that need approvals:"
+msgstr[0] "There are unconfirmed angels in %d angel type. Angel type that needs approval:"
+msgstr[1] "There are unconfirmed angels in %d angel types. Angel types that need approvals:"
```
Comment (xuwhite) [inline resources/lang/en_US/default.po]: Angel types that need approvals: => Angel types that need approval:

**Comment by xuwhite** [comment]
for the theme commit please also fix this
Screenshot 2026-01-15 at 18 58 58

**Comment by xuwhite** [comment]
Screenshot 2026-01-15 at 19 04 55
please add more space above the error

**Comment by xuwhite** [comment]
The progress bar color doesn't work for me
Screenshot 2026-01-15 at 19 09 07

File: includes/view/User_view.php [hunk 3]
```diff
@@ -317,7 +322,7 @@ function User_view_shiftentries($needed_angel_type)
         . '">' . htmlspecialchars($needed_angel_type['name']) . '</a>:</b> ';
 
     $shift_entries = [];
-    foreach (collect($needed_angel_type['users'])->sortBy('name') as $user_shift) {
+    foreach (collect($needed_angel_type['users'])->sortBy('name', SORT_STRING | SORT_FLAG_CASE) as $user_shift) {
```
Comment (xuwhite) [inline includes/view/User_view.php:326]: please sort by name after sorting by params

**Comment by xuwhite** [comment]
I'm done with my review 🎉

File: includes/view/User_view.php (hunk 3 above)
Comment (MyIgel) [reply includes/view/User_view.php:326]: not the right place but sure

**Comment by xuwhite** [comment]
Screenshot 2026-01-17 at 14 18 44
please also darken "X"

**Comment by xuwhite** [comment]
Screenshot 2026-01-17 at 14 20 29
This is in desperate need of contrast too
