### PR TITLE
fix: use mb_stripos for case-insensitive search with umlauts

### LINKED ISSUE #1317: Case sensitive search for umlauts
The search function, e.g. on `/admin-active`, is case-sensitive with regards to umlaute. That is, searching for `ä` does not yield accounts  which only have `Ä` in their name; likewise, `ö` and `Ö` as well as `ü` and `Ü`.

### PR DESCRIPTION
**Pull request by teal-bauer**
PHP's `stristr()` function is not multibyte-aware, which means searching for lowercase umlauts (ä, ö, ü) won't match their uppercase equivalents (Ä, Ö, Ü). For example, searching for "ü" would fail to find users named "MÜLLER".

This affects the admin search pages for active users, free angels, and arrivals. The fix replaces `stristr()` with `mb_stripos()`, which handles multibyte characters correctly for case-insensitive matching.

Added a test to verify that umlaut searching works case-insensitively with `mb_stripos`. The application already uses UTF-8 throughout (database charset is utf8mb4, PHP's mb_internal_encoding is UTF-8), so no encoding issues to worry about.

Fixes #1317

### CODE REVIEW

**Comment by teal-bauer** [comment]
Extended to also add ASCII folding per #606 - searching "muller" now finds "Müller", "celine" finds "céline", etc. Uses PHP's Intl Transliterator.

File: tests/Unit/Helpers/StringSearchTest.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+    /**
+     * @dataProvider provideAsciiFoldingCases
+     */
+    public function testAsciiFoldingSearch(
+        string $haystack,
+        string $needle,
+        bool $expectedFound
+    ): void {
+        $normalize = fn($s) => transliterator_transliterate('Any-Latin; Latin-ASCII; Lower', $s) ?: mb_strtolower($s);
```
Comment (MyIgel) [inline tests/Unit/Helpers/StringSearchTest.php]: Testing the third copy of an anonymous function is not the best idea as they will diff at some point.
Moving it to a helper (`src/helpers.php`) is imho the better place.

File: includes/pages/admin_active.php [hunk 2]
```diff
@@ -241,7 +242,7 @@ function admin_active()
             $match = false;
             foreach ($tokens as $t) {
                 $t = trim($t);
-                if (!empty($t) && stristr($user->name, $t)) {
+                if (!empty($t) && mb_stripos($normalize($user->name), $normalize($t)) !== false) {
```
Comment (MyIgel) [inline includes/pages/admin_active.php]: Using `\Illuminate\Support\Str::contains` here is more explicit and thus easier to read (without much overhead)

File: tests/Unit/Helpers/StringSearchTest.php (hunk 1 above)
Comment (teal-bauer) [reply tests/Unit/Helpers/StringSearchTest.php]: Yeah I wasn't sure if this needed tests at all since it's standard library stuff. Not sure what the helper would contain though, the lambda is already pretty tiny?

File: includes/pages/admin_active.php (hunk 2 above)
Comment (teal-bauer) [reply includes/pages/admin_active.php]: But Illuminate Str::contains doesn't do any normalization? Or do you mean sth like `Str::contains($normalize(...), $normalize(...))`?

Comment (teal-bauer) [reply includes/pages/admin_active.php]: Illuminate also does mb_strtolower for each needle, and then non-mb str_contains for each (needle,haystack), I am not sure those are all equivalent to mb_stripos?

Comment (teal-bauer) [reply includes/pages/admin_active.php]: Checked PHP docs: after `mb_strtolower`, `str_contains` does byte comparison. So "MÜLLER" → "müller", but `str_contains("müller", "muller")` is false because the ü bytes (C3 BC) don't match u (75).

So `Str::contains` handles case but not diacritics. For this PR we need both - that's what the Transliterator does (strips diacritics before comparison).

**Comment by teal-bauer** [comment]
Moved the normalize lambda to `normalize_for_search()` helper in `src/helpers.php`. Tests now cover the helper directly.

File: src/helpers.php [hunk 3]
```diff
@@ -228,3 +228,12 @@ function view(?string $template = null, array $data = []): Renderer|string
...
     return $renderer->render($template, $data);
 }
+
+/**
+ * Normalize a string for search comparison.
+ * Converts to ASCII and lowercase for diacritic-insensitive matching.
+ */
+function normalize_for_search(string $s): string
+{
+    return transliterator_transliterate('Any-Latin; Latin-ASCII; Lower', $s) ?: mb_strtolower($s);
```
Comment (MyIgel) [inline src/helpers.php]: After some tests it would be great to add `Any-NFKC` beforehand so that for example `42m²` can be found by using `42m2`.
Also adding `"ext-intl": "*",` to `composer.json` makes it explicit that the php intl extension is used.

**Comment by teal-bauer** [comment]
Added `Any-NFKC` before `Any-Latin`, and added `ext-intl` as explicit composer require, tests updated.
